import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Tasks from '../components/tasks/tasks'
import Blur from '../public/blury.svg'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head>
      <div className={styles.mainContainer}>
      <div className='container'>
      <img src={Blur.src} />
      <h4>Your TODOs</h4>
      <main className={styles.main}>
          <Tasks />
      </main>
      </div>
      </div>
    </>
  )
}
